name: DSL
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.05.30=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.9=h7f8727e_0
  - pip=23.1.2=py38h06a4308_0
  - python=3.8.16=h955ad1f_4
  - readline=8.2=h5eee18b_0
  - setuptools=67.8.0=py38h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py38h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - alembic==1.11.1
    - certifi==2023.5.7
    - charset-normalizer==3.1.0
    - cmaes==0.9.1
    - cmake==3.26.4
    - colorlog==6.7.0
    - contourpy==1.1.0
    - cycler==0.11.0
    - filelock==3.12.2
    - fonttools==4.40.0
    - greenlet==2.0.2
    - idna==3.4
    - importlib-metadata==6.7.0
    - importlib-resources==5.12.0
    - jinja2==3.1.2
    - kiwisolver==1.4.4
    - lit==16.0.6
    - mako==1.2.4
    - markupsafe==2.1.3
    - matplotlib==3.7.1
    - mpmath==1.3.0
    - networkx==3.1
    - numpy==1.24.4
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - optuna==3.2.0
    - packaging==23.1
    - pandas==2.0.3
    - pillow==10.0.0
    - pyparsing==3.1.0
    - python-dateutil==2.8.2
    - pytz==2023.3
    - pyyaml==6.0
    - requests==2.31.0
    - seaborn==0.12.2
    - six==1.16.0
    - sqlalchemy==2.0.17
    - sympy==1.12
    - torch==2.0.1
    - torchvision==0.15.2
    - tqdm==4.65.0
    - triton==2.0.0
    - typing-extensions==4.7.1
    - tzdata==2023.3
    - urllib3==2.0.3
    - zipp==3.15.0